/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.edisoncor.gui.util.WindowsUtil;

/**
 *
 * @author an3-r
 */
public class Cargando extends javax.swing.JFrame implements Runnable{
    Login fmPrincipal = new Login();
    Thread hilo;
    /**
     * Creates new form Cargando
     */
    public Cargando() {
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        initComponents();
        setLocationRelativeTo(null);

                
        txtCreditos.setText("<html><p align=\"justify\">CorpoSoft diseño y programacion por Andres Ramirez, Copyright "
                            + " todos los derechos reservados se prohibe la reproduccion total o parcial de este software"
                + " Java aplicación Version beta V0.1 2017 contacto Corposoft10@gmail.com</p></html> ");
        
    }
    
    public Image getIconImage(){
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Iconos/LogoAplication.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgressBar = new javax.swing.JProgressBar();
        lblEstado = new javax.swing.JLabel();
        txtCreditos = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CorpoSoft Inicando...");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgressBar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        ProgressBar.setForeground(new java.awt.Color(51, 0, 204));
        getContentPane().add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 577, 22));

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Cargando Iconos...");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 580, 21));

        txtCreditos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(txtCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 550, 64));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner sofpo.fw.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 410, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/loader_48x48.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargando().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel txtCreditos;
    // End of variables declaration//GEN-END:variables


    @Override
    public void run() {
        this.setVisible(true);//ventana visible
        ProgressBar.setStringPainted(true);
        WindowsUtil.makeWindowsOpacity(this,0.8f);//transparencia
        try {
            for(int i=0; i<=100; i++ ){
               
               ProgressBar.setValue(i);
               hilo.sleep(50); //tiempo de espera en segundos multiplicado por el numero 1 del ciclo for
               if(i==10){
                   lblEstado.setText("Cargando Interfaz Grafica.");
                   Thread.sleep(1000);
                   
               }else if(i==12){
                   lblEstado.setText("Cargando Interfaz Grafica..");
                   Thread.sleep(1200);
                   
               }else if(i==14){
                   lblEstado.setText("Cargando Interfaz Grafica...");
                   Thread.sleep(900);
                   
               }else if(i==21){
                   lblEstado.setText("Cargando Librerias");
                   Thread.sleep(1200);
                   
               }else if(i==34){
                   lblEstado.setText("Cargando TimingFramework");
                   Thread.sleep(1000);
                   
               }else if(i==48){
                   lblEstado.setText("Cargando Paquetes");
                   
                   
               }else if(i==52){
                   lblEstado.setText("Acediendo a la base de datos");
                   Thread.sleep(500);
                   lblEstado.setText("Interfas colingnigt");
               }else if(i==66){
                   lblEstado.setText("Leyendo Informacion");
                   
                   
               }else if(i==82){
                   lblEstado.setText("Cargando Bibliotecas");
                   Thread.sleep(800);
                   
               }else if(i==85){
                   lblEstado.setText("Iniciando.");
                    Thread.sleep(500);
                   
                   
               }else if(i==86){
                   lblEstado.setText("Iniciando..");
                   Thread.sleep(500);
                   
                   
               }else if(i==87){
                   lblEstado.setText("Iniciando...");
                   Thread.sleep(500);
                   
                   
               }else if(i==88){
                   lblEstado.setText("Iniciando.");
                   Thread.sleep(500);
                   
                   
               }else if(i==89){
                   lblEstado.setText("Iniciando..");
                   Thread.sleep(500);
                   
                   
               }else if(i==90){
                   lblEstado.setText("Iniciando...");
                   Thread.sleep(500);
                   
                   
               }
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(Cargando.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();//Ocultar ventana
        fmPrincipal.setVisible(true);//mostar ventana principal
        
       
    }
    }