/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Model.Conexion;
import Controlador.Metodos;
import static Vista.Login.conn;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author an3-r
 */
public class Licencia extends javax.swing.JDialog {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    
    Metodos MT=new Metodos();
    /**
     * Creates new form Licencia
     */
    public Licencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        activacion();
    }
    
    void activacion(){
        int diasint=MT.SerialDias();
        if(diasint<=0){
         lblDiasActivacion.setText("Su versión de prueba expiro realice la activación ahora.");   
        }else{
        
        String dias=Integer.toString(diasint);      
        lblDiasActivacion.setText("Te quedan "+dias+" días para realizar la activación.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDiasActivacion = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        btnActivarProducto = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Simson", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Advertencia");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Esta es una versión de prueba");

        lblDiasActivacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiasActivacion.setText("Te quedan 1 días para realizar la activación.");

        txtSerial.setBackground(new java.awt.Color(102, 102, 102));
        txtSerial.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtSerial.setForeground(new java.awt.Color(255, 255, 255));
        txtSerial.setText("00000-00000-00000-00000");

        btnActivarProducto.setFont(new java.awt.Font("Thunderstrike", 0, 18)); // NOI18N
        btnActivarProducto.setText("Activar");
        btnActivarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActivarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarProductoActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Activacion156x156px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActivarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDiasActivacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogo)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(lblDiasActivacion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarProductoActionPerformed
        String serial=""; 
        try {
            conn=Conexion.Enlace(conn);
            Statement st=conn.createStatement();
            
            ResultSet rs=st.executeQuery("SELECT serial FROM system ");
            rs.next();
            serial=rs.getString(1);
            
            
        } catch (Exception e) {
            System.out.println("Error al consultar el serial");
        }
        if(txtSerial.getText().equals(serial)){
             try {
            // actualizando la primera tabla

            PreparedStatement pst = conn.prepareStatement("UPDATE system SET validacion='1' WHERE id=1 ");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"La licencia se aplicó con éxito\n"
                    + "ahora puede disfrutar de la versión full","Activación Exitosa",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            Login fmPrincipal = new Login();
            fmPrincipal.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,""+e);
        }
        }else{
            JOptionPane.showMessageDialog(null,"La licencia es incorrecta","Error Activación",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActivarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Licencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Licencia dialog = new Licencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDiasActivacion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
