/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
import org.edisoncor.gui.util.WindowsUtil;



/**
 *
 * @author an3-r
 */
public class Login extends javax.swing.JFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    Metodos NombreUser=new Metodos();
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        txtUsuer.grabFocus();
        //PanelDatos.setOpaque(false);  para poner transparente un elemento
        
        
        
    }
    
    public Image getIconImage(){
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Iconos/LogoAplication.png"));
        return retvalue;
    }
    
    public void Login(){
        String TipoUser="";
        String id_user="";
        String password="";
        String validacion="";
        //Estado slicitud variables
        String EstadoSolicitud="";
        
        id_user=txtUsuer.getText();
        password=Password.getText();
        
        try {
            conn=Conexion.Enlace(conn);
            Statement st=conn.createStatement();
            
            ResultSet rs=st.executeQuery("SELECT count(*) FROM login WHERE id_user='"+id_user+"' and password='"+password+"'");
            rs.next();
            validacion=rs.getString(1);
            
            
            
            
        } catch (Exception e) {
            System.out.println("Error al consultar la tabla LOGIN "+e);
        }
        
        try {
            conn=Conexion.Enlace(conn);
            Statement st=conn.createStatement();
            
            ResultSet rs=st.executeQuery("SELECT tipo_user FROM login WHERE id_user='"+id_user+"' and password='"+password+"'");
            rs.next();
            TipoUser=rs.getString(1);
            
            
        } catch (Exception e) {
            System.out.println("Error al consultar la tabla LOGIN en el campo TIPO USUARIO");
        }
        
        
        Metodos Met=new Metodos();
        
        if(validacion.equals("1")&& TipoUser.equals("User")){
            
                DataLogin user = DataLogin.getSingletonInstance(id_user);//Mandamos el numero para saber el nombre
                //Met.UltimoIngreso(id_user);
                JOptionPane.showMessageDialog(null,"Bienvenido "+NombreUser.NombreUser(id_user,"cliente")+" a CorpoSoft!","BIENVENIDO",JOptionPane.INFORMATION_MESSAGE);
            User obj=new User();
            obj.setVisible(true);
            dispose();
            
            
        }else if(validacion.equals("1")&& TipoUser.equals("Admin") ){
            DataLogin user = DataLogin.getSingletonInstance(id_user);//Mandamos el numero para saber el nombre
            
            JOptionPane.showMessageDialog(null,"Usted es un Administrador Bienvenido "+NombreUser.NombreUser(id_user,"funcionario")+" a CorpoSoft!","Administrador Bienvenido",JOptionPane.INFORMATION_MESSAGE);
            Administrador obj=new Administrador();
            obj.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Contraseña o Usuario Incorrecto","Error Datos Incorrectos",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuer = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogoGif = new javax.swing.JLabel();
        lblLogoAplication = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Inicio de sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Thunderstrike 3D", 0, 24))); // NOI18N
        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Usuario:");
        PanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña:");
        PanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtUsuer.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtUsuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuerActionPerformed(evt);
            }
        });
        PanelDatos.add(txtUsuer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 230, -1));

        Password.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        PanelDatos.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, -1));

        btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Entrar.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        PanelDatos.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 96, 30));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        PanelDatos.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 102, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Olvide la Contraseña.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        PanelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        getContentPane().add(PanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 439, 287));

        lblLogoGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.gif"))); // NOI18N
        lblLogoGif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoGif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoGifMouseClicked(evt);
            }
        });
        lblLogoGif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblLogoGifKeyTyped(evt);
            }
        });
        getContentPane().add(lblLogoGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogoAplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca de agua.fw.png"))); // NOI18N
        getContentPane().add(lblLogoAplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 300, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtUsuer.setText("");
        Password.setText("");
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // Boton entrar
        Login();
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        Login obj=new Login();
       obj.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        // TODO add your handling code here:
        char cTeclaPresionada=evt.getKeyChar();
        
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            
            btnEntrar.doClick();
            
        }
        
    }//GEN-LAST:event_PasswordKeyTyped

    private void txtUsuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuerActionPerformed

    private void lblLogoGifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblLogoGifKeyTyped
        
    }//GEN-LAST:event_lblLogoGifKeyTyped

    private void lblLogoGifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoGifMouseClicked
        JOptionPane.showMessageDialog(null, "Hasta Pronto...", "Cerrando Aplicación", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_lblLogoGifMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(evt.getClickCount() == 2){
            new RecordarContrasena(this, true).setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Thread(new Cargando()).start();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogoAplication;
    private javax.swing.JLabel lblLogoGif;
    private javax.swing.JTextField txtUsuer;
    // End of variables declaration//GEN-END:variables
}
