/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Model.*;
import Controlador.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import org.edisoncor.gui.util.WindowsUtil;



/**
 *
 * @author an3-r
 */
public class Login extends javax.swing.JFrame implements Runnable{
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    Metodos NombreUser=new Metodos();
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    
    java.util.Date now=new java.util.Date();
    java.text.SimpleDateFormat sdf=new
    java.text.SimpleDateFormat("dd-MM-yy");
    Thread h1;
    String fecha="";
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        txtUsuer.grabFocus();
        this.setTitle("Inicio de sección");
        fecha=sdf.format(now);
        h1 = new Thread(this);
        h1.start();
        //PanelDatos.setOpaque(false);  para poner transparente un elemento
        
       
        
    }
    
    public Image getIconImage(){
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Iconos/LogoAplication.png"));
        return retvalue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        txtUsuer = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        lblPass = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogoGif = new javax.swing.JLabel();
        lblRelog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setIconImage(getIconImage());
        setResizable(false);

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Inicio de sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Thunderstrike", 0, 24))); // NOI18N
        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuer.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        txtUsuer.setBorder(null);
        txtUsuer.setOpaque(false);
        txtUsuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuerActionPerformed(evt);
            }
        });
        PanelDatos.add(txtUsuer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 300, 50));

        Password.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Password.setBorder(null);
        Password.setOpaque(false);
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        PanelDatos.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 300, 50));

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pass_txt.png"))); // NOI18N
        lblPass.setPreferredSize(new java.awt.Dimension(347, 50));
        PanelDatos.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Aceptar/acep_norm.png"))); // NOI18N
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Aceptar/acep_press.png"))); // NOI18N
        btnEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Aceptar/acep_roll.png"))); // NOI18N
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        PanelDatos.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 40));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Limpiar/limpiar_norm.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Limpiar/limpiar_press.png"))); // NOI18N
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosMejorados/Limpiar/limpiar_roll.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        PanelDatos.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Olvide la Contraseña.");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        PanelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user_txt.png"))); // NOI18N
        lblUser.setPreferredSize(new java.awt.Dimension(347, 48));
        PanelDatos.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 66, -1, 60));

        lblLogoGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_principal_v2.0.png"))); // NOI18N
        lblLogoGif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoGif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoGifMouseClicked(evt);
            }
        });
        lblLogoGif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblLogoGifKeyTyped(evt);
            }
        });

        lblRelog.setFont(new java.awt.Font("Sho-Card-Caps", 1, 36)); // NOI18N
        lblRelog.setForeground(new java.awt.Color(0, 51, 255));
        lblRelog.setText("00:00.00 AM");
        lblRelog.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fecha y hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 18))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblLogoGif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblRelog, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lblRelog, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(lblLogoGif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtUsuer.setText("");
        Password.setText("");
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        Login obj=new Login();
       obj.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        // TODO add your handling code here:
        char cTeclaPresionada=evt.getKeyChar();
        
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            
            btnEntrar.doClick();
            
        }
        
    }//GEN-LAST:event_PasswordKeyTyped

    private void txtUsuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuerActionPerformed

    private void lblLogoGifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblLogoGifKeyTyped
        
    }//GEN-LAST:event_lblLogoGifKeyTyped

    private void lblLogoGifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoGifMouseClicked
        JOptionPane.showMessageDialog(null, "Hasta Pronto...", "Cerrando Aplicación", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_lblLogoGifMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(evt.getClickCount() == 1){
            new RecordarContrasena(this, true).setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    public javax.swing.JPasswordField Password;
    public javax.swing.JButton btnEntrar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoGif;
    private javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblRelog;
    private javax.swing.JLabel lblUser;
    public javax.swing.JTextField txtUsuer;
    // End of variables declaration//GEN-END:variables

 @Override
    public void run() {
        Thread ct= Thread.currentThread();
        
        while(ct==h1){
            calcula();
            lblRelog.setText(fecha+" "+hora+":"+minutos+":"+segundos+" "+ampm);
            try{
                Thread.sleep(1000);
            }catch(InterruptedException e){}
        }
        
        
    }
    
    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        java.util.Date fechaHoraActual = new java.util.Date();
        
        calendario.setTime(fechaHoraActual);
        ampm= calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }else{
            hora= calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY); 
        }
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }

}
